root: true
extends:
  - cheminfo-react/base
  - cheminfo-typescript/base
  - cheminfo-typescript/unicorn
rules:
  'import/default': off
  'import/no-unresolved': off
  'react-refresh/only-export-components': off
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/restrict-plus-operands': off
  'react/no-unstable-nested-components': off
  no-restricted-imports:
    - error
    - name: '@simbathesailor/use-what-changed'
      message: 'Remove use-what-changed before committing the code'
  react/no-unknown-property:
    - error
    - ignore:
        - 'css'
parserOptions:
  sourceType: module