name: Node.js Dev Checking

on:
  push:
    branches-ignore:    
        - 'main'   
        - 'development'   
  pull_request:
    branches:
        - development

jobs:
    e2etest:
        uses: NFDI4Chem/nmrium-react-wrapper/.github/workflows/e2e.yml@main 
    lint:
        uses: NFDI4Chem/nmrium-react-wrapper/.github/workflows/nodejs.yml@main 
            