name: Node.js check

on:
  workflow_call:  

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run eslint
      - name: Run Prettier
        run: npm run prettier
      - name: Check types
        run: npm run check-types